### ISSUE TITLE
Scary error page with scarrier messages

### ISSUE THREAD

**Issue by gogolander** [Movimento5StelleLazio/ParlamentoElettronicoM5S#280]
The error page does not contain an italian translation of the error message and the "report the bug" button provide a bug warning to Liquid Feedback project instead of us.

**Comment by gogolander** [comment]
the new page must contain the italian version of the message, the english version of the message and report the bug sending a mail to bug@parelon.com, as discussed yesterday: I will do the triage.
Before starting to write the messages, plz check if there already exist the translation.

**Comment by mwithi** [comment]
We have several ways to do it:
1. classic href="mailto:bug@parelon.com"
2. precompiled mailto (we may include the stacktrace)
3. redirect to a form to guide the user in compiling the report

The system_error page involved in the issue is not related to translations files, is a static html. Should we convert into a Lua page?

Is there a server class in charge for sending mails?

The German translation will disappear?
